name: Build / Test / Deploy
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: my-project # TODO: update to your Google Cloud project ID
  REGION: us-central1 # TODO: update to your region
  SERVICE: my-service # TODO: update to your service name

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
      - name: Lint & Build
        working-directory: ./app
        run: npm ci && npm run lint && npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./app/out